### PR TITLE
Add favicon.ico

### LINKED ISSUE #14: 更換網站 favicon
## Why is this change necessary
- 更有整體性
## Proposed solution
- 尋找免費 icon 或畫一個簡單的圖示來取代目前的網站 favicon
## Definition of done
- 更換 favicon 並 deploy production

---
## Things to do

Ref: https://github.com/audreyr/favicon-cheat-sheet
- [x] Draw a favicon in Pixelmator
- [x] Export it to PNG with Alpha Channel
- [x] Declare Favicon in HTML

### PR DESCRIPTION
**Pull request by yorkxin**
solves https://github.com/taiwanese-work-in/foreign-country/issues/14
## Why is this change necessary?
- To resolve #14 
## How does it address the issue?
- Added a favicon at the website root.

### CODE REVIEW

**Comment by ascendbruce** [comment]
Do you consider also declaring in the web page footer?

**Comment by yorkxin** [comment]
I think declaring in the repository is good enough? Since we have a link to the source code repository.

**Comment by ascendbruce** [comment]
I prefer not to take risk on the legal side (sorry was busy last few days)

**Comment by yorkxin** [comment]
Alright. I will add it to the footer.

**Comment by yorkxin** [comment]
done!

**Comment by ascendbruce** [comment]
Thanks! @chitsaou

**Pull request merged**
